---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
      time: "06:00"
    commit-message:
      # Prefix all commit messages with "chore: "
      prefix: "chore"