---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
      time: "06:00"
    commit-message:
      # Prefix all commit messages with "chore: "
      prefix: "chore"

  - package-ecosystem: "pip"
    directory: "pytest-bdd-sample/harness"
    schedule:
      interval: daily
      time: "06:00"
    commit-message:
      prefix: "chore"

  - package-ecosystem: "npm"
    directory: "wdio-sample/harness"
    schedule:
      interval: daily
      time: "06:00"
    commit-message:
      prefix: "chore"